ci:
  collect:
    headful: false,
    url: https://kodaskills.github.io/kodaskills.co/
    settings:
      chromeFlags: --disable-gpu --no-sandbox --no-zygote
  assertions:
      categories:performance: ['error', {minScore: 0.9}]
      categories:accessibility: ['error', {minScore: 0.9}]
      categories:best-practices: ['error', {minScore: 0.9}]
      categories:seo: ['error', {minScore: 0.9}]
      categories:pwa: ['error', {minScore: 0.9}]