default-src: "'self'"
script-src: "'self'"
style-src: "'self' https://fonts.googleapis.com"
img-src: "'self' data:"
font-src: "'self' https://fonts.gstatic.com"
connect-src: "'self'"
object-src: "'none'"
base-uri: "'self'"
form-action: "'self'"
