#
#   Refer for explanation to following link:
#   https://github.com/evilmartians/lefthook/blob/master/docs/configuration.md
#
#   ❗ For special local purposes please use lefthook-local.yml instead of changing this file
#   ❗ We use lefthook in CI/CD, so please add tag "no-ci" to bypass a command on CI/CD
#
pre-push:
  parallel: true
  commands:
    "Audit packages":
      tags: security
      run: npm audit
    "Check git branch":
      tags:
        - convention
        - no-ci
      run: npx --yes validate-branch-name
    "Check unused files, dependencies...":
      tags: maintenance
      run: npm run knip
pre-commit:
  parallel: true
  commands:
    "Run tests":
      tags: test
      run: npm test
    "Check and fix code format and lint":
      tags: convention
      run: |
        npx --yes @biomejs/biome check --write --no-errors-on-unmatched --files-ignore-unknown=true {staged_files}
        command -v just && just --fmt --unstable && find just -name '*.just' -exec just --fmt --unstable -f $1 {} \;
        if [ "${CI}" != "true" ]; then
          git update-index --again
        fi
commit-msg:
  commands:
    "Check commit message":
      tags:
        - convention
        - no-ci
      run: npx --yes -- commitlint --edit "$1"
