ci:
  assert:
    assertions:
      first-contentful-paint:
      - error
      - minScore: 0.9
  collect:
    # staticDistDir: "./dist"
    startServerCommand: npm run preview
    startServerReadyPattern: http://localhost:4322
    url: http://localhost:4322