ci:
  assert:
    assertions:
      first-contentful-paint:
        - error
        - minScore: 0.9
  collect:
    startServerCommand: npm run preview
    startServerReadyPattern: http://host.docker.internal:host:4322
    url: http://localhost:4322
