services:
  astro:
    build: .
    container_name: astro
    ports:
      - "${ASTRO_SERVER_PORT}:4321"
      - "${ASTRO_SERVER_PREVIEW_PORT}:4322"
    working_dir: /home/node/
    volumes:
      - .:/home/node
      - node_modules:/home/node/node_modules
    command: npm run dev
    develop:
      watch:
        - action: rebuild
          path: package.json
          target: /

volumes:
  node_modules:
