name: Continuous Deployment

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types: [completed]

permissions:
  contents: read
  actions: read
  pull-requests: read
  id-token: write

jobs:
  deploy-cloudflare:
    name: ☁️ Deploy to Cloudflare Pages
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.workflow_run.event == 'push' && 'production' || 'preview' }}
      url: ${{ steps.deploy.outputs.deployment-url }}
    env:
      DEPLOY_BRANCH: ${{ github.event.workflow_run.head_branch }}
      DEPLOY_COMMIT: ${{ github.event.workflow_run.head_sha }}
      NOTIFY_PR_TITLE: ${{ github.event.workflow_run.pull_requests[0].title || github.event.workflow_run.head_commit.message }}
      NOTIFY_PR_NUMBER: ${{ github.event.workflow_run.pull_requests[0].number || 0 }}
      NOTIFY_PR_URL: ${{ github.event.workflow_run.pull_requests[0].html_url }}
    steps:
      - name: 📦 Checkout
        uses: actions/checkout@v6

      - name: 📦 Setup
        uses: ./.github/actions/setup-bun

      - name: Debug
        run: |
          echo "***** DEBUG EVENT WORKFLOW RUN *****"
          echo "${{ github.event.workflow_run.pull_requests }} " | jq '.'

      - name: 📥 Download dist artifact
        uses: actions/download-artifact@v8
        with:
          name: dist
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path: dist/

      - name: 🚀 Deploy
        id: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./dist --project-name=${{ vars.CLOUDFLARE_PROJECT_NAME }} --branch=${{ env.DEPLOY_BRANCH }} --commit-hash=${{ env.DEPLOY_COMMIT }}

      - name: 💬 Slack notification
        if: always()
        uses: ./.github/actions/slack-notify
        with:
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          job_status: ${{ job.status }}
          pr_title: ${{ env.NOTIFY_PR_TITLE }}
          pr_number: ${{ env.NOTIFY_PR_NUMBER }}
          deploy_url: ${{ steps.deploy.outputs.deployment-url }}
          pr_url: ${{ env.NOTIFY_PR_URL }}
          commit_hash: ${{ env.DEPLOY_COMMIT }}
