name: Continuous Deployment

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types: [completed]

permissions:
  contents: read
  actions: read
  pull-requests: read
  id-token: write

jobs:
  deploy-cloudflare:
    name: ☁️ Deploy to Cloudflare Pages
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.workflow_run.event == 'push' && 'production' || 'preview' }}
      url: ${{ steps.deploy.outputs.deployment-url }}
    env:
      DEPLOY_BRANCH: ${{ github.event.workflow_run.head_branch }}
      NOTIFY_PR_TITLE: ${{ github.event.workflow_run.pull_requests[0].head.ref }}
      NOTIFY_PR_NUMBER: ${{ github.event.workflow_run.pull_requests[0].number }}
      NOTIFY_PR_URL: https://github.com/${{ github.repository }}/pull/${{ github.event.workflow_run.pull_requests[0].number }}/
    steps:
      - name: 📦 Checkout
        uses: actions/checkout@v6

      - name: 📦 Setup
        uses: ./.github/actions/setup-bun

      - name: 🚀 Deploy
        id: deploy
        uses: ./.github/actions/deploy-cloudflare
        with:
          artifact_name: dist
          dist_path: ./dist
          project_name: ${{ vars.CLOUDFLARE_PROJECT_NAME }}
          branch: ${{ env.DEPLOY_BRANCH }}
          pr_number: ${{ env.NOTIFY_PR_NUMBER }}
          api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          account_id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          run_id: ${{ github.event.workflow_run.id }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: 💬 Slack notification
        if: always()
        uses: ./.github/actions/slack-notify
        with:
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          job_status: ${{ job.status }}
          pr_title: ${{ env.NOTIFY_PR_TITLE }}
          pr_number: ${{ env.NOTIFY_PR_NUMBER }}
          deploy_url: ${{ steps.deploy.outputs.deployment-url }}
          pr_url: ${{ env.NOTIFY_PR_URL }}
          project_name: Website
